language: generic

script:
  - make
  - make test

sudo: false

matrix:
  include:
    - os: linux
      dist: trusty
      compiler: gcc48
      env:
        - CC=gcc-4.8
        - CXX=g++-4.8
      addons:
        apt:
          sources:
            - kalakris-cmake
            - ubuntu-toolchain-r-test
          packages:
            - gcc-4.8
            - g++-4.8
            - libxml2-dev
            - ninja-build
            - cmake
    - os: osx
      osx_image: xcode7.2
      compiler: clang
      before_install:
        - brew update
      install:
        - brew reinstall cmake
        - brew reinstall ninja
