language: generic

script:
  - make
  - make test

sudo: false

matrix:
  include:
    - os: linux
      dist: trusty
      compiler: gcc
      addons:
        apt:
          sources: kalakris-cmake
          packages:
            - libxml2-dev
            - ninja-build
            - cmake
    - os: osx
      osx_image: xcode7.2
      compiler: clang
      before_install:
        - brew update
      install:
        - brew reinstall cmake
        - brew reinstall ninja
